### ISSUE TITLE
Level up point can be added

### ISSUE THREAD

**Issue by xunyangjian1** [KurwaClown/KALUS#16]
Level up point can be added

**Comment by xunyangjian1** [comment]
![image](https://github.com/KurwaClown/KALUS/assets/77496534/a7ded66f-e8a3-4697-a0b6-7fda0d2f9e98)
what's this when i open client

**Comment by KurwaClown** [comment]
Hey, so basically this happens when there is an error (i'm still trying to make the app handle the errors correctly).
If you see another error like this you can just click the button labeled "copy report link" and you paste it into your browser. You should then reach the issue page with a full description of the bug that i will be able to use for fixing it.

Or you can describe to me how the bugged happens here if you want
